### PR TITLE
Implement check to see whether user multiple clusters

### LINKED ISSUE #38: Require cluster name to install app to / default cluster to apply app install to
Currently, even if a user only has one kubernetes cluster and they run `civo apps add app_name` on its own the CLI errors out hard.

Options: Either,
- Make the cluster name a non-optional flag
- Default the cluster name to the user's only cluster IF no flag provided AND IF user only has 1 cluster running on their account.

### PR DESCRIPTION
**Pull request by kaihoffman**
If a user does not specify a cluster to install a kubernetes app to, checks
if the user has multiple clusters. If only one cluster is found, installs
specified app to that cluster. If multiple clusters found, lets user know.
Closes #38 when merged

### CODE REVIEW

**Comment by andyjeffries** [comment]
I'd be tempted to just make `Finder.detect_cluster(cluster)` return the only cluster if `cluster.blank?` and there is only one cluster. Rather than have this logic in the level above Finder. Feels like it should be an internal feature of that method.

**Comment by kaihoffman** [comment]
I knew there was a more logical way to do it - sorry, clearly still cold-addled!

**Comment by andyjeffries** [comment]
No worries mate, we all sometimes need a second pair of eyes to spot something that would have jumped out to us on another day.

**Comment by kaihoffman** [comment]
I've done that and it's looking much simpler now :)

**Pull request merged**
